Forex lite
vanGe1ion/ReactForexPanel pull request #1
Opened 2022-02-21 08:31 UTC by vanGe1ion

Project was cleaned. Forex Lite Panel is ready

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +      "http://data.fixer.io/api/latest?access_key=ea516aed6f2b591d600566b784ae5350&format=1",
Не нужно жестко в коде указывать URL и уж тем более API ключи, сразу стащат боты накупят серваков и начнут майнить (у нас уже было такое).
Вынеси URL в константу, а API лучше вообще в переменные окружения
https://www.npmjs.com/package/dotenv
https://create-react-app.dev/docs/adding-custom-environment-variables/

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +    );
А если не законектиться? catch тоже нужно обработать

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +        setValue1("100");
Не ну чо ты так сразу то пессимистично, мы только 88 пробили еще. А если серьезно то я не думаю эти строки нужны, ты тут по сути просто неправильный курс показываешь. Лучше в initial состояние закинуть EUR/RUB с курсом 0

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +  const [exchange1, setExchange1] = useState("");
Плохие имена переменных, они должны быть понятные (пример: exchangeRateFrom) иначе ты потом сам в коде не поймешь что творится , а уж другой разработчик и подавно.

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +  const [value1, setValue1] = useState("");
Если это понял для значений (см. выше про имена переменных), то зачем ты строки здесь хранишь (и ниже проверяешь их на isNumber) не проще ли здесь просто числа использовать, а для полей type=number (https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/number)?

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +    Fetch(
У тебя выше в пакетах axios подключен, зачем ты тогда его тащишь если все равно с fetch работаешь

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +        getActual(data.date);
Опять таки плохое название метода, у тебя эта функция под капотом делает setActual, а метод называется getActual. У тому-же сама функция состоит их одной строки, так может сразу сюда саму функцию сеттер прислать, а не оборачивать в что-то что еще и называется крайней обманчиво

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +  }, [toggled]);
А зачем так хитро? Почему просто не вызывать toggleExchange когда нажат переключатель?

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +    if (isNaN(Number(value1))) return "Некорректный ввод";
См. выше коммент про тип поля

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +        <input
Я бы это вытащил в отдельный компонент

2022-02-21 09:34 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +        <input value={value2} onChange={() => {}} type="text" />
1. не нужно onChange пустой лепить если ты все равно его не используешь
2. Тут тоже нужна функция которая в обратную сторону конверит (т.е. если я в этом поле значение меняю - в соседнем тоже пересчитывается (пример: https://www.google.com/search?q=usd+rub, попробуй поменять оба поля, соседнее при этом тоже считается)

2022-02-21 09:34 UTC, reshetov commented on src/utils/script.js
> +export async function Fetch(get, callback) {
Переименуй в что-нибудь другое, допустим в fetchRates. Я уже оставил тебе вышел комментарий о том что ты юзаешь fetch когда есть axios, а ты просто метод так похоже завал (коммент я удалю).

2022-02-21 09:34 UTC, reshetov commented on src/utils/script.js
> +  try {
у axios свой catch есть - https://axios-http.com/docs/handling_errors

2022-02-21 09:34 UTC, reshetov commented on src/utils/script.js
> +    alert("Ошибка запроса к внешнему ресурсу: " + e);
Не нужно алертов, не пугай пользователя. Лучше просто верни пустой объект и в консоль напиши что не удалось курсы обновить

2022-02-21 09:42 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +  const [value1, setValue1] = useState("");
нет. на Намбер проверяется поле по ключу. Я хотел сразу зашить коэффициенты в селект и не городить огород, но всплыла проблема с одинаковыми коэффициентами. Привы боре доллара выбиралось поле с таким же показатель, встреченное в опциях первыми. пришлось пересесть на строки и вытаскивать множители из стейта по ключу

2022-02-21 09:43 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +  const [value1, setValue1] = useState("");
и проверка поля по ключу на число как раз не дает выводить NaN в результат

2022-02-21 09:46 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +      "http://data.fixer.io/api/latest?access_key=ea516aed6f2b591d600566b784ae5350&format=1",
а куда собственно константу положить? лучше отдельный файл?

2022-02-21 09:48 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +        setValue1("100");
почему неправильный? это конверт 100 EUR в RUB

2022-02-21 09:50 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +        <input value={value2} onChange={() => {}} type="text" />
я понял. просто посчитал, что оно неуправляемо, раз мы отдельным элементом тогглим валюты

2022-02-21 09:53 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +        <input value={value2} onChange={() => {}} type="text" />
ну а пустым обработчик заткнул варнинг, каюсь) глаза мазолил

2022-02-21 09:56 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +    );
ну тогда можно оставить там пустые поля?

2022-02-21 09:57 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +        <input
сделаем

2022-02-21 10:03 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +      "http://data.fixer.io/api/latest?access_key=ea516aed6f2b591d600566b784ae5350&format=1",
Да. В папке с компонентов создай отдельный файл и в него закинь

2022-02-21 10:03 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +  const [value1, setValue1] = useState("");
Давай пока это скипнем, посмотрим что получится после остальных правок и там уже решим

2022-02-21 10:03 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +        setValue1("100");
Да, только курс евро сегодня 87,39, а завтра будет еще какой-нибудь. А у тебя 1-100 и может получиться ситуация когда у тебя не загрузятся курсы (нет связи с API). А пользователь как раз хотел евро в рубли махнуть. И что он увидит? Что 1 евро - 100 рублей, поменяет, а потом поймет что "что-то не так", кто ему деньги возвращять будет?
А в моем варианте 0 меняется на 0 - деньги мы точно не потеряем

2022-02-21 11:13 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +        setValue1("100");
не согласен. в моем случае курс лежит в стейте. exchange1 и 2 - по сути наименование валюты, используются как ключи для доступа к множителю из стейта. value1 и 2 - значения сумм для конвертации. при инициализации устанавливаем валюту и левую сумму (в нашем случае слева 100 евро), и валюту, в которую конвертим. согласен, что value2 можно не ставить. так или иначе при фейле загрузки все значения по умолчанию остаются пустымии обмана никакого не будет. по поводу актуальности курсов выведена дата, соответственно для обновления курсов на следующий день нужно перезагрузить страницу. при фейле ситуация описана выше, при успехе получим актуальную конвертацию 100 евро в рубли

2022-02-21 14:49 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +      "http://data.fixer.io/api/latest?access_key=ea516aed6f2b591d600566b784ae5350&format=1",
сделано

2022-02-21 14:49 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +  const [exchange1, setExchange1] = useState("");
сделано

2022-02-21 14:49 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +        <input
сделано

2022-02-21 14:49 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +        <input value={value2} onChange={() => {}} type="text" />
сделано

2022-02-21 14:49 UTC, vanGe1ion commented on src/utils/script.js
> +export async function Fetch(get, callback) {
сделано

2022-02-21 14:50 UTC, vanGe1ion commented on src/utils/script.js
> +  try {
сделано. но так получилось, что катч у аксиос ловит только внутренние ошибки, а ошибки запроса надо обрабатывать отдельно

2022-02-21 14:50 UTC, vanGe1ion commented on src/utils/script.js
> +    alert("Ошибка запроса к внешнему ресурсу: " + e);
сделано

2022-02-22 07:17 UTC, Isidora25 requested changes

2022-02-22 07:17 UTC, Isidora25 commented on src/API/forexAPI.js
> +    FOREX_API,
Не очень понятно, что хранится в этой константе. Имена переменных и констант должны быть максимально прозрачными и понятными, чтобы любому разработчику, читающему код, было понятно, что лежит в этой переменной. Например, если в константе лежит ссылка на апи, то ее можно назвать примерно так FOREX_API_URL

2022-02-22 07:17 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +      setCurrency1("EUR");
Для всех ридонли цифровых и строковых констант следует создавать переменную const именованную в SNAKE_UPPER_CASE и хранить их в специальном файле

2022-02-22 07:17 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +        4
Строка 43 и 47 отличаются только порядком переменных. А в остальном идентичны. Если приходится использовать один и тот же код несколько раз, это верный признак того, что код нужно выносить в переменную или в функцию и переиспользовать. Это позволит вносить изменения только в одном месте, если это будет необходимо в будущем. А так же сократит количество кода.

2022-02-22 07:17 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +    if (currentInput === 1) setValue2(calculate());
Не очень понятно, что такое 1 и 2. Если положить эти значения в константы с читаемым именем, будет намного понятнее.

2022-02-22 07:17 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +          rateList={Object.keys(rateList)}
Набор тегов внутри `ConverterGroup`  повторяется дважды. Их нужно вынести в компонент, который можно будет вызывать два раз, просто передав ему различные аргументы.

2022-02-22 07:17 UTC, Isidora25 commented on .env
> +REACT_APP_FIXER_IO_PRIVATE_KEY=ea516aed6f2b591d600566b784ae5350
Файл .env нужно добавить в гит игнор. Этот файл не должен попадать в репозиторий, так как в нем обычно хранят всякие ключи и креды. Если этот файл оставить, то его очень легко достать из репозитория и использовать в своих целях. Этим обычно занимаются не очень хоршие люди, а проблемы будут потом у владельца репозитория. 
Для того чтобы показать другим разработчикам, какой набор `env` переменных нужен для приложения, создается файл ` env.example `, в который помещаются только названия переменных с недостоверными или пустыми значениями.

2022-02-22 07:19 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +      setCurrency1("EUR");
О каких константах в данном случае речь?

2022-02-22 08:40 UTC, vanGe1ion commented on .env
> +REACT_APP_FIXER_IO_PRIVATE_KEY=ea516aed6f2b591d600566b784ae5350
сделано

2022-02-22 08:40 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +          rateList={Object.keys(rateList)}
сделано

2022-02-22 08:40 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +    if (currentInput === 1) setValue2(calculate());
сделано

2022-02-22 08:40 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +        4
сделано

2022-02-22 08:41 UTC, vanGe1ion commented on src/API/forexAPI.js
> +    FOREX_API,
сделано

2022-02-22 08:44 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +      setCurrency1("EUR");
`"EUR" ` etc

2022-02-22 08:50 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +      setCurrency1("EUR");
сделано

2022-02-22 08:53 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +  const [currency1, setCurrency1] = useState("");
Еще раз  (и надеюсь в последний) - поменяй имена переменных. value1, currency2 и т.п. названия не делают, потому в дальнейшем в коде будет категорически непонятно что происходит на строке:
`const value1000 = value99 * value3 + currency7/value4`
Переменная должна показывать для чего именно она используется

2022-02-22 08:56 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +  const [currency1, setCurrency1] = useState("");
проблема в цифрах, теперь понял.

2022-02-22 09:19 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +  const [currency1, setCurrency1] = useState("");
сделано

2022-02-22 09:40 UTC, Isidora25 requested changes

2022-02-22 09:40 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +        numerator1: amountFirst,
Как уже писал Андрей, не стоит называть параметры с цифровыми приписками. Пусть каждое имя параметра отражает его смысл.

2022-02-22 09:40 UTC, Isidora25 commented on src/utils/utils.js
> +  if (members.denominator1 === 0 || members.denominator2 === 0) return null;
Используй декструктуризацию const { a, b ,c} = members. 
Тогда не придется каждый раз обращаться к объекту members, сократив тем самым количество кода

2022-02-22 09:40 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +    if (currentInput === NUMBER_INPUT_FIRST)
кажется, тут можно упросить и передать `currentInput` сразу как параметр функции `calculateExchange`

2022-02-22 09:40 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +    let proportinMembers = {};
кажется, здесь опечатка в названии переменной

2022-02-22 09:40 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +    if (currentInput === NUMBER_INPUT_FIRST) setValue2(calcResult);
здесь отлично подойдет тернарный оператор

2022-02-22 09:43 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +  const [currency1, setCurrency1] = useState("");
Ок, давай перепишем строку по другому:
`const amountOneThousand = amountNinetyNine * amountThree + currencySeven / valueFour`
сильно стало понятнее?
А если так `const amountTotal = amountFrom * amountByRate + currencyTo / amountTo` ?

2022-02-22 09:44 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +    let proportinMembers = {};
исправил

2022-02-22 09:50 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +  const [currency1, setCurrency1] = useState("");
направления  from и to теряют свой смысл, если мы можем производить конвертацию в любую сторону, да еще и свапать ее. не вижу в таком наименовании ничего понятного, только больше путаницы. в таком случае префиксы left/right и то будут читаться лучше, разве нет?

2022-02-22 10:05 UTC, reshetov commented on src/components/Converter/Converter.jsx
> +  const [currency1, setCurrency1] = useState("");
Поле "from" это поле из которого идет конвертация (по логике левое, т.к. мы читаем слева-направо), поле "to" соответственно то в которое идет конвертация (правое у нас), какое именно поле мы меняем не важно, у нас всегда конвертация "из валюты в валюту". Если брать этот случай как "частный", то можно допустить имена полей в виде Left/Right (но что делать если полей будет три или мы будем жить в арабской стране где  везде right to left)
Смотри, давай я еще раз уточню, мы сейчас пытаемся не написать с тобой конвернер (у меня их штук 15 наверное в репозиториях), а научить тебя грамотно писать код. А красивый код это код который читается как обычный текст, а не заставляет ревьюера или напарника сидеть и читать голову в попытках разобрать его

2022-02-22 10:09 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +  const [currency1, setCurrency1] = useState("");
да я понимаю.  просто когда в коде встретится конструкция аля setSomeFrom(someTo), мой внутренний компилятор будет орать как резаный что тут какая то ересь

2022-02-22 11:27 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +    if (currentInput === NUMBER_INPUT_FIRST) setValue2(calcResult);
сделано

2022-02-22 11:33 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +    if (currentInput === NUMBER_INPUT_FIRST)
сделал

2022-02-22 11:33 UTC, vanGe1ion commented on src/utils/utils.js
> +  if (members.denominator1 === 0 || members.denominator2 === 0) return null;
сделал

2022-02-22 11:33 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +        numerator1: amountFirst,
сделал

2022-02-22 11:52 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +  const [currency1, setCurrency1] = useState("");
поставил from/to имена

2022-02-22 12:04 UTC, Isidora25 approved these changes

2022-02-22 12:04 UTC, Isidora25 commented on src/components/Converter/Converter.jsx
> +    switch (inputCurrent) {
А для чего свитч кейс? Тут всего два варианта для условия, достаточно тернарника

2022-02-22 12:04 UTC, Isidora25 commented on src/components/consts.js
> +// export const CURRENCY_SECOND_INIT_VALUE = "RUB";
Не оставляй закомментированный код. Код либо нужен, либо нет. Если что-то возможно понадобится в будущем,то можно посмотреть в истории коммитов

2022-02-22 12:06 UTC, vanGe1ion commented on src/components/Converter/Converter.jsx
> +    switch (inputCurrent) {
справедливо

2022-02-22 12:16 UTC, vanGe1ion commented on src/components/consts.js
> +// export const CURRENCY_SECOND_INIT_VALUE = "RUB";
сделано

2022-02-22 12:40 UTC, Isidora25 requested changes

2022-02-22 12:40 UTC, Isidora25 commented on src/components/consts.js
> +export const FOREX_API_URL = "http://data.fixer.io/api/latest";
это где-то используется? Неиспользуемый код нужно удалять

2022-02-22 12:40 UTC, Isidora25 commented on src/API/forexAPI.js
>  export const getForex = async (callback) => {
если это больше не используется в проекте, то нужно удалить

2022-02-22 12:42 UTC, vanGe1ion commented on src/API/forexAPI.js
>  export const getForex = async (callback) => {
и в первом, и в этом случае это времянка для проверки кода из за израсходованного лимита запросов на основном сервисе

2022-02-22 12:48 UTC, vanGe1ion commented on src/API/forexAPI.js
>  export const getForex = async (callback) => {
окей, переиграно и уничтожено

2022-02-22 12:48 UTC, vanGe1ion commented on src/components/consts.js
> +export const FOREX_API_URL = "http://data.fixer.io/api/latest";
окей, переиграно и уничтожено

2022-02-22 12:49 UTC, vanGe1ion commented on src/API/forexAPI.js
>  export const getForex = async (callback) => {
как Маэстро завещал

2022-02-24 06:26 UTC, Isidora25 approved these changes

2022-02-24 06:35 UTC, merged